### PR TITLE
Configurable write_http Timeout

### PR DESCRIPTION
**Pull request by udaysagar2177**

### CODE REVIEW

**Comment by mdubbyap** [comment]
Can we add BufferSize to this as well?  It is very likely something customers will want.

**Comment by udaysagar2177** [comment]
Ok Matt, I will add BufferSize and update here

**Comment by udaysagar2177** [comment]
@mdubbyap I have included an option for BufferSize

**Comment by udaysagar2177** [comment]
@ramjothikumar has given a green flag to this. Merging it!

**Pull request merged**
